### PR TITLE
Convert the sequence diagrams to plantuml

### PR DESCRIPTION
**Pull request by snorp**
Convert the sequence diagrams to plantuml

### CODE REVIEW

**Comment by snorp** [comment]
I think this is nicer than the manual ASCII art, but not sure if it will work with the automated builds. I guess we'll see?

**Comment by snorp** [comment]
This also needs a change to fix up the SVG output here https://github.com/martinthomson/i-d-template/pull/357

**Comment by martinthomson** [comment]
The style changes should be ready to go now.

Though maybe you could also try out [aasvg](https://github.com/martinthomson/aasvg).  It probably won't handle the "-.-.-." lines well though.

**Comment by snorp** [comment]
I'm working on fixing the horizontal squashing. Not really sure which part of the pipeline is causing that problem, though.

**Comment by martinthomson** [comment]
xml2rfc - with its default HTML styling - generates SVG figures that are scaled to 100% of the width of the bounding box.  This results in squashing if the diagram is large (the number varies, but the default stylesheet goes up to about 900px) or stretching if the diagram is small.  The stylesheet I use only sets max-width, so it doesn't stretch, but it does so for a narrower width than the default so it will squash more aggressively if the figures are too big.

Large figures are a real problem with tools like plantuml (or mermaid, which I find integrates better, by the way).  The only suggestion I have is to look for ways to make your diagram smaller.  That will help with readability anyway.

**Comment by snorp** [comment]
Thanks for the explanation. I saw the `max-width` in `i-d-template`, but it's not clear to me how the `viewBox` and `width` attributes are generated for the SVG. You can tell `plantuml` to omit those, but they show up in the HTML output regardless, so I guess something else is coming up with a "natural" dimension for the SVG somewhere? Maybe xml2rfc?

I wanted to use `mermaid` initially as I've enjoyed using it for other things, but was scared off by the comment in the `kramdown-rfc` `README`: "Very experimental; the conversion to SVG is prone to generate black-on-black text in this version". I tried it just now and a simple sequence diagram seems to choke on invalid `font-weight` attributes in `xml2rfc`, so maybe I'm missing some additional configuration?

**Comment by martinthomson** [comment]
Sorry, I don't know how `viewBox` and `width` are generated in different tools.  I can only speak to `aasvg`, which sets all of the dimension attributes.  My understanding is that `xml2rfc` doesn't touch sizing attributes, but will complain about `width` (a complaint I ignore).

It might be possible to tweak `kramdown-rfc` to filter out any offending attributes, like `font-weight` [here](https://github.com/cabo/kramdown-rfc/blob/93427e543b09bbdd651cdac90aa930eb609fe2ac/lib/kramdown-rfc2629.rb#L441-L450) if you have trouble.  `svgcheck` also has the `-r` option, which strips out anything it doesn't know about.

**Comment by snorp** [comment]
I added some bits to install `plantuml` when running in CI (untested in CI, however). I also tried to fix the diagram to look better with the limited width.

**Comment by snorp** [comment]
Screenshot 2023-01-06 8 48 04 AM

**Comment by dimmyvi** [comment]
xml2rfc fails with the new diagram: https://github.com/dimmyvi/tigress/actions/runs/3856131963/jobs/6612919761
I had similar issue when I tried to insert an svg image to the doc

**Comment by snorp** [comment]
Ah, it seems I screwed up the `plantuml` installation stuff, as the `lint` rule (obviously, in retrospect) does not run before the xml generation. @martinthomson , I think I need to add stuff to the `deps` target, right? Or add things to `DEPS_FILES`? The latter didn't work for me, but the former did with this PR https://github.com/martinthomson/i-d-template/pull/360

**Comment by martinthomson** [comment]
I've improved documentation for adding dependencies in https://github.com/martinthomson/i-d-template/commit/52201af9fef3bb9c00a06caa16494b1854eec4d3

**Comment by snorp** [comment]
@martinthomson sorry for being dense, but that still doesn't seem to be working for me -- latest attempt in [77cbf8875546f7c5086aac5444718521b323b797](https://github.com/dimmyvi/tigress/commit/77cbf8875546f7c5086aac5444718521b323b797)

**Comment by martinthomson** [comment]
The action isn't running (maybe because @dimmyvi) hasn't approved.  So no evidence that it works (or not).

Hmm, that looks basically fine to me in structure. The catch is that the image that this runs within for CI runs is not the default GitHub CI image, but one that I maintain.  That uses alpine, not ubuntu.  So for CI you need `apk add --no-cache plantuml` instead of `apt-get install`.

**Comment by martinthomson** [comment]
I've added a few more pointers to the documentation.

**Comment by martinthomson** [comment]
@snorp, I just realized that ordering matters.  You might also find that you need to put the change to DEPS_FILES at the top of the Makefile.

**Comment by martinthomson** [comment]
...and I realize that you can't easily tweak the inclusion in DEPS_FILES based on `$(CI)`...  The way to address that is to change the rule as follows:

```make
plantuml_marker := .whatever
DEPS_FILES += $(plantuml_marker)
LIBDIR := lib
include $(LIBDIR)/main.mk

# boilerplate here

$(plantuml_marker):
        @if $(CI); then apk add --no-cache plantuml; elif ! hash plantuml >/dev/null; then ! echo "plantuml is not installed"; fi
        @touch $@

# other targets

**Comment by snorp** [comment]
Ah! Thanks, that seems to be working now with `CI=true make` locally. We'll see if the Actions are happy if @dimmyvi kicks it :)

**Comment by dimmyvi** [comment]
Ran the action, it still fails: https://github.com/dimmyvi/tigress/actions/runs/3879254464/jobs/6629587218

**Comment by snorp** [comment]
@dimmyvi I pushed a plausible fix, can you kick it again?

**Comment by snorp** [comment]
I found a way to run it locally and it's still broken. Investigating further. Ugh.

**Comment by snorp** [comment]
Alright, seems to work locally now with the Action. Hopefully it also works on GitHub.

**Comment by dimmyvi** [comment]
Action has succeeded now

**Review by dimmyvi — APPROVED** [review]

**Pull request merged**
